### ISSUE TITLE
Error installing AM2R on Ubuntu/Pop!_OS

### ISSUE THREAD

**Issue by PhoenixUp** [AM2R-Community-Developers/AM2RLauncher#34] opened 2022-09-28 14:39 UTC
Whenever I hit install after choosing my AM2R file it throws me a weird error
![Screenshot from 2022-09-28 10-36-03](https://user-images.githubusercontent.com/114595546/192808618-b04fadb2-d121-43c0-95db-0a90b6dea6bc.png)

**Comment by Miepee** [comment] 2022-09-28 14:53
Hi thanks for reporting the issue!
Please do not ignore the bug report template, as it helps immensely.
Could you attach info about your OS and a log file?

**Comment by PhoenixUp** [comment] 2022-09-28 16:10
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/9666875/AM2RLauncher.log)
I'm using Pop!_OS 22.04 LTS and the launcher version is the flatpack v2.2.0

**Comment by Miepee** [comment] 2022-09-28 16:13
Thanks, this is a duplicate of #33 
A WIP solution can be found [at this comment in that issue](https://github.com/AM2R-Community-Developers/AM2RLauncher/issues/33#issuecomment-1260504118)

**Closed by Miepee** 2022-09-28 16:13 UTC
Labels: bug
