### ISSUE TITLE
Flatpak: Clicking "Play" in the Launcher just minimizes and unminimizes the Launcher without actually launching the game.

### ISSUE THREAD

**Issue by DaniPhoFani** [AM2R-Community-Developers/AM2RLauncher#37] opened 2022-11-21 19:56 UTC
**Describe the bug**:
Having trouble getting AM2R to run on Steam Deck using the AM2R launcher. I downloaded it from the Discover store and followed all the steps for the Steam Deck users here: https://github.com/AM2R-Community-Developers/AM2RLauncher/wiki/Installation-Process

But when I click "Play" in the Launcher, the Launcher just minimizes itself and then pops right back up, no game. 

**Expected behavior**:
For AM2R To launch on Steam Deck using the AM2R Launcher from Discover

**To Reproduce**
1. Download the AM2RLauncher via the Discover Store on Steam Deck
2. Click Download
3. Select AM2R V 1.1 Zip file
4. let it run
5. Click Play

**Screenshots**

**Platform**
 - OS: Steam OS 3.3.2
 - AM2RLauncher Version: 2.3.0
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10060137/AM2RLauncher.log)
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10060141/AM2RLauncher.log)

**Additional context**

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10060149/AM2RLauncher.log)

**Comment by Miepee** [comment] 2022-11-21 21:11
All good.
Out of curiosity, if you go to the Mod Settings, create a Desktop shortcut, launch the desktop shortcut, close the game, does starting the game then from the launcher work?

**Comment by Miepee** [comment] 2022-11-21 21:29
Reopened, as this should not happen. Game should launch without one needing to create the desktop shortcut first as that's an optional feature.

**Comment by DaniPhoFani** [comment] 2022-11-21 21:32
I'm just happy I can play the game on Deck now, but if you need any more information from me feel free to reach out.

**Comment by Miepee** [comment] 2022-12-24 17:53
Noting for reference, that this is not steamdeck specific, it also happened to Jes under Opensuse tumbleweed

**Comment by 6XGate** [comment] 2023-01-14 00:12
The desktop icon is not usable on Fedora or any Linux distro that uses GNOME with no desktop icon extension.

**Comment by Lojemiru** [comment] 2023-01-14 00:14
We quite literally discovered the cause of this bug about 3 minutes before your reply - we're not entirely sure of the fix yet, but we're looking into it and should have an update sometime soon.

**Comment by Miepee** [comment] 2023-01-14 00:15
> The desktop icon is not usable on Fedora or any Linux distro that uses GNOME with no desktop icon extension.

Hi, can you create a new bug report for this please? This issue is just for tracking the "cannot launch am2r on flathub" bug

**Comment by 6XGate** [comment] 2023-01-14 00:23
> > The desktop icon is not usable on Fedora or any Linux distro that uses GNOME with no desktop icon extension.
> 
> Hi, can you create a new bug report for this please? This issue is just for tracking the "cannot launch am2r on flathub" bug

#41 has been filed

**Comment by Miepee** [comment] 2023-01-14 00:38
Fixed by d1419c6a088509d8079ccaf4d36d8bda0fe47bf9

**Closed by Miepee** 2023-01-14 00:38 UTC
Labels: bug
