### ISSUE TITLE
[Linux Mint] ERROR AM2RLauncher.MainForm - The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by jjhen99** [AM2R-Community-Developers/AM2RLauncher#79] opened 2024-05-22 16:27 UTC
**Describe the bug**
I am trying to install AM2R Launcher. When I click on the green 'download' button I get this: 'ERROR AM2RLauncher.MainForm - The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.' More details are in the log file.

I am using Linux Mint 21.3 (Virginia)
I am using AM2Launcher 2.3.0

I have the following .NET Core Runtimes installed: 
Microsoft.NETCore.App 6.0.28 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

![AM2R Error 3](https://github.com/AM2R-Community-Developers/AM2RLauncher/assets/141966475/755d5d08-abb0-4c46-a9ca-e133219e19a7)

**Log file**
[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/15406188/AM2RLauncher.log)

I also commented about this error in this thread: https://github.com/AM2R-Community-Developers/AM2RLauncher/issues/40

**Comment by Miepee** [comment] 2024-05-22 17:33
Duplicate of that linked thread #40.
We just havent made a new release yet, so that change hasnt rolled out to users yet.

**Closed by Miepee** 2024-05-22 17:33 UTC
Labels: bug
